version: '3.7'

services:
  dm_db:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgressql/data
    environment:
       POSTGRES_PASSWORD: 12345
       POSTGRES_USER: postgres
       POSTGRES_DB: test_blog
  django:
    container_name: blog
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/dm_rest/manage.py migrate --noinput && python /usr/src/dm_rest/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/dm_rest
    ports:
      - 8000:8000
    depends_on:
      - dm_db

volumes:
    pg_data:
